// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83wvbH9m4lig4Qy_IMm25wvMbRlAThIs',
    appId: '1:244742856089:web:403544fcefc4f75cd3c708',
    messagingSenderId: '244742856089',
    projectId: 'login-app-amaljsam',
    authDomain: 'login-app-amaljsam.firebaseapp.com',
    storageBucket: 'login-app-amaljsam.firebasestorage.app',
    measurementId: 'G-V45Q6CQPY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5TIHNtDBUYhFMAbZoyfP8M17xqP0qf2w',
    appId: '1:244742856089:android:4870d99be7a912f9d3c708',
    messagingSenderId: '244742856089',
    projectId: 'login-app-amaljsam',
    storageBucket: 'login-app-amaljsam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-QblS95Xs4aFTqxzDSHzCybgG3oySrm4',
    appId: '1:244742856089:ios:dc727f6b3945be2bd3c708',
    messagingSenderId: '244742856089',
    projectId: 'login-app-amaljsam',
    storageBucket: 'login-app-amaljsam.firebasestorage.app',
    iosBundleId: 'com.amaljsam.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-QblS95Xs4aFTqxzDSHzCybgG3oySrm4',
    appId: '1:244742856089:ios:dc727f6b3945be2bd3c708',
    messagingSenderId: '244742856089',
    projectId: 'login-app-amaljsam',
    storageBucket: 'login-app-amaljsam.firebasestorage.app',
    iosBundleId: 'com.amaljsam.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB83wvbH9m4lig4Qy_IMm25wvMbRlAThIs',
    appId: '1:244742856089:web:41b1b8a6d03f7125d3c708',
    messagingSenderId: '244742856089',
    projectId: 'login-app-amaljsam',
    authDomain: 'login-app-amaljsam.firebaseapp.com',
    storageBucket: 'login-app-amaljsam.firebasestorage.app',
    measurementId: 'G-CGTXW7EVRW',
  );
}
